name: Build and release Next.js web applications
on: push
jobs:
  build-project:
    name: Build Next.js application
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm install
      - name: Build static website
        run: npm run build