name: Deploy Next.js Application

on:
  workflow_run:
    workflows: ['Build and Upload Next.js Artifacts']
    types: [completed]

jobs:
  deploy:
    name: Deploy Next.js Application
    runs-on: self-hosted

    steps:
      # Step 1: Download Build Artifacts
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build
          path: ./artifact

      # Step 2: Debug Artifact Contents
      - name: Verify Artifact Contents
        run: ls -la ./artifact/

      # Step 3: Deploy Application to Server
      - name: Deploy Application to Server
        run: |
          scp -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} -r ./artifact/.next/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/pi/nextjs-app/.next/

      # Step 4: Restart Application
      - name: Restart Application
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
          cd /home/pi/nextjs-app
          npm install --production
          pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start
          EOF
