name: Deploy Next.js Application

on:
  workflow_run:
    workflows: ['Build and Upload Next.js Artifacts']
    types: [completed]

jobs:
  deploy:
    name: Deploy Next.js Application
    runs-on: self-hosted

    

    steps:
      # Step 1: Clear Target Directory
      - name: Clear Artiface Directory
        run: rm -rf ./praveengovind_artifact/*
      # Step 2: Download Build Artifacts
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build
          path: ./praveengovind_artifact
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        
      # Step 3: Debug Artifact Contents
      - name: Verify Artifact Contents
        run: ls -la ./praveengovind_artifact/

      # Step 4: Create Target Directory
      - name: Create Target Directory
        run: mkdir -p /home/pgovind/Public/WWW/PraveenGovind/praveengovind/Site/

      # Step 4: Clear Target Directory
      - name: Clear Target Directory
        run: rm -rf /home/pgovind/Public/WWW/PraveenGovind/praveengovind/Site/*

      # Step 5: Copy Files to Target Directory
      - name: Copy Files
        run: cp -r ./praveengovind_artifact/* /home/pgovind/Public/WWW/PraveenGovind/praveengovind/Site/
      # Step 6: Set File Permissions
      - name: Fix Permissions
        run: |
          sudo chown -R pgovind:pgovind /home/pgovind/Public/WWW/PraveenGovind/praveengovind/Site/
          sudo chmod -R 755 /home/pgovind/Public/WWW/PraveenGovind/praveengovind/Site/
      # Step 7: Install dependencies
      - name: Install Dependencies (if needed)
        run: |
          cd /home/pgovind/Public/WWW/PraveenGovind/praveengovind/Site/
          npm install --production
       # Step 8: build production version
      - name: Install Dependencies (if needed)
        run: |
            cd /home/pgovind/Public/WWW/PraveenGovind/praveengovind/Site/
            npm run build --production

      # Step 9: Restart Application
      - name: Restart Application
        run: |
          export PATH=$PATH:/usr/local/bin
          export PM2_HOME=/home/pgovind/.pm2
          pm2 describe nextjs-app || pm2 start npm --name "nextjs-app" -- start
          pm2 restart nextjs-app --update-env

      # Step 10: Save PM2 Process
      - name: Save PM2 Process
        run: |
          export PATH=$PATH:/usr/local/bin
          export PM2_HOME=/home/pgovind/.pm2
          pm2 save