name: Deploy Next.js Application

on:
  workflow_run:
    workflows: ['Build and Upload Next.js Artifacts']
    types: [completed]

jobs:
  deploy:
    name: Deploy Next.js Application
    runs-on: self-hosted

    
    steps:
      # Step 1: Download Build Artifacts
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build
          path: ./praveengovind_artifact
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        
      # Step 2: Debug Artifact Contents
      - name: Verify Artifact Contents
        run: ls -la ./praveengovind_artifact/

      # Step 3: Create Target Directory
      - name: Create Target Directory
        run: mkdir -p /home/pgovind/Public/WWW/PraveenGovind/praveengovind/Site/

      # Step 4: Copy Files to Target Directory
      - name: Copy Files
        run: cp -r ./praveengovind_artifact/* /home/pgovind/Public/WWW/PraveenGovind/praveengovind/Site/

      # Step 5: Restart Application
      - name: Restart Application
        run: |
          export PATH=$PATH:/usr/local/bin
          export PM2_HOME=/home/pgovind/.pm2
          cd /home/pgovind/Public/WWW/PraveenGovind/praveengovind/Site/
          npm install --production
          pm2 describe nextjs-app || pm2 start npm --name "nextjs-app" -- start
          pm2 restart nextjs-app --update-env

      # Step 6: Save PM2 Process
      - name: Save PM2 Process
        run: |
          export PATH=$PATH:/usr/local/bin
          export PM2_HOME=/home/pgovind/.pm2
          pm2 save