name: Deploy Next.js Application

on:
  workflow_run:
    workflows: ['Build and Upload Next.js Artifacts']
    types: [completed]

jobs:
  deploy:
    name: Deploy Next.js Application
    runs-on: self-hosted

    

    steps:
      # Step 1: Clear Target Directory
      - name: Clear Artiface Directory
        run: rm -rf ./praveengovind_artifact/*
      # Step 2: Download Build Artifacts
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build
          path: ./praveengovind_artifact
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        
      # Step 3: Debug Artifact Contents
      - name: Verify Artifact Contents
        run: ls -la ./praveengovind_artifact/

      # Step 4: Create Target Directory
      - name: Create Target Directory
        run: mkdir -p /home/pgovind/Public/WWW/PraveenGovind/praveengovind/Site/

      # Step 4: Clear Target Directory
      - name: Clear Target Directory
        run: rm -rf /home/pgovind/Public/WWW/PraveenGovind/praveengovind/Site/*

      # Step 5: Copy Files to Target Directory
      - name: Copy Files
        run: cp -r ./praveengovind_artifact/* /home/pgovind/Public/WWW/PraveenGovind/praveengovind/Site/
      # Step 6: Set File Permissions
      - name: Fix Permissions
        run: |
          cd /home/pgovind/Public/WWW/PraveenGovind/praveengovind/Site/
      # Step 7: Set File Permissions
      - name: Fix Permissions
        run: |
          chown -R pgovind:pgovind /home/pgovind/Public/WWW/PraveenGovind/praveengovind/Site/
          find /home/pgovind/Public/WWW/PraveenGovind/praveengovind/Site/ -type d -exec chmod 755 {} \;
          find /home/pgovind/Public/WWW/PraveenGovind/praveengovind/Site/ -type f -exec chmod 644 {} \;
      # Step 8: Install Dependencies (if required)
      - name: Install Dependencies
        run: |
          cd /home/pgovind/Public/WWW/PraveenGovind/praveengovind/Site/
          npm install
      # Step 9: Install Dependencies (if required)
      - name: Install Dependencies
        run: |
          cd /home/pgovind/Public/WWW/PraveenGovind/praveengovind/Site/
          npm run build
      # Step 10: Restart Application
      - name: Restart Application with PM2
        run: |
          export PATH=$PATH:/usr/local/bin
          export PM2_HOME=/home/pgovind/.pm2
          pm2 describe nextjs-app > /dev/null 2>&1
          if [ $? -eq 0 ]; then
            echo "Restarting existing PM2 process..."
            pm2 restart nextjs-app --update-env
          else
            echo "Starting a new PM2 process..."
            pm2 start npm --name "nextjs-app" -- start
          fi

      # Step 11: Save PM2 Process
      - name: Save PM2 Process
        run: |
          export PATH=$PATH:/usr/local/bin
          export PM2_HOME=/home/pgovind/.pm2
          pm2 save