name: Deploy Next.js Application

on:
  workflow_run:
    workflows: ['Build and Upload Next.js Artifacts']
    types: [completed]

jobs:
  deploy:
    name: Deploy Next.js Application
    runs-on: self-hosted

    steps:
      # Step 1: Download Build Artifacts
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build
          path: ./praveengovind_artifact
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        
      # Step 2: Debug Artifact Contents
      - name: Verify Artifact Contents
        run: ls -la ./praveengovind_artifact/

      # Step 2: Create Target Directory
      - name: Create Target Directory
        run: mkdir -p /home/pgovind/Public/WWW/PraveenGovind/praveengovind/Site/

      # Step 3: Copy Files to Target Directory
      - name: Copy Files
        run: cp -r /home/pgovind/Public/WWW/PraveenGovind/praveengovind/praveengovind_artifact/* /home/pgovind/Public/WWW/PraveenGovind/praveengovind/Site/

      # Step 4: Restart the Application
      - name: Restart Application
        run: |
          cd /home/pgovind/Public/WWW/PraveenGovind/praveengovind/Site/
          npm install --production
          pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start